todoproject/todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todoapp'
urlpatterns = [
    path('', views.add, name="add"),
    # path('details',views.details,name="details"),
    path('delete/<int:taskid>/',views.delete,name="delete"),
    path('update/<int:id>/', views.update,name="update"),
    path('cbvhome/',views.TaskListview.as_view(),name='cbvhome'),
    path('cbvdetails/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetails'),
    path('cbvupdate/<int:pk>/',views.TaskUpdateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.TaskDeleteview.as_view(),name='cbvdelete'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("todoapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()


    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from . models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.urls import reverse_lazy
from . models import Task
from django.shortcuts import render, redirect
from . forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


class TaskListview(ListView):
    model=Task
    template_name='home.html'
    context_object_name = 'task1'

class TaskDetailview(DetailView):
    model=Task
    template_name = 'details.html'
    context_object_name = 'task'

class TaskUpdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields=('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetails', kwargs={'pk': self.object.id})

class TaskDeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')

def add(request):
    task1=Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1':task1})

# def details(request):
#     task=Task.objects.all()
#     return render(request,'detail.html',{'task':task})

def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')


def update(request,id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  <p> Are you sure this task is done?</p>
  <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproject/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for i in task %}
{{i.name}}
{{i.priority}}
{% endfor %}
</body>
</html>

todoproject/templates/details.html
{% extends 'base.html' %}
{% block content %}
<div class="shadow card">
     <div class="card-body">
         <h5 class="card-title">{{task.name}}</h5>
         <p><b>{{task.priority}}</b></p>
         <p><b>{{task.date}}</b></p>
         <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
         <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>
     </div>
</div>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{f.as_p}}
  <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
                {% csrf_token %}
                  <div class="form-group">
                     <input type="text" class="form-control"  name="task" placeholder="Enter your task name">
                        </div><br>
                <div class="form-group">
                 <input type="text" class="form-control" name="priority" placeholder="Enter the priority task">
                 </div><br>
                <div class="form-group">
                 <input type="date" class="form-control" name="date" placeholder="Enter the date">
                 </div><br>
                <input type="submit" class="btn btn-success"><br><br>
                </form>

        </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in task1 %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}