movieproject/movieapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name="add_movie"),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]
app_name = 'movieapp'

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    title=models.TextField()
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','title','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,"index.html",context)

def detail(request,movie_id):
    movie1=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie1})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row"  style="padding:20px;">

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text" name="name" placeholder="Enter your movie name"><br><br>
    <input type="text" name="title" placeholder="Enter the title"><br><br>
    <input type="text" name="desc" placeholder="Enter the description"><br><br>
    <input type="text" name="year" placeholder="Enter the year"><br><br>
    <input type="file" name="img"><br><br>
    <input type="submit">
</form>
    </div>
</div>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
   <meta charset="UTF-8">
   <title>Title</title>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color: #704241";>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark" >
         <div class = "navbar-header" >
             <div class="navbar-fixed-top">
                <a class="navbar-brand" href="#">

    Online Movie Store
  </a>
    </div>
         </div>
            <a href="{% url 'movieapp:add_movie' %}" class="btn btn-outline-success navbar-btn">Add Movies</a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<html>
<body style="background-color:#666666">
<form method="POST">
  {% csrf_token %}
  <h4 style="padding:20px;">Are you sure?
  You want to delete the movie?<br>
  </h4>
  <input type="submit">
</form>

</body>
</html>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
<img src="{{movie.img.url}}" width="400" height="400">
        </div>
<div class="col-md-6">
<h2 style="color:white">{{movie.name}}({{movie.year}})</h2><br>
<h4 style="text-align:justify">{{movie.desc}}</h4><br>
<!--<h4>{{movie.year}}</h4><br>-->
<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
</div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<html>
<body style="background-color: lightgreen";>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}

  <input type="submit">

</form>
</body>
</html>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row"  style="padding:10px;">
        {% for i in movie_list %}
<!--        <div class="col-md-4">-->
            <div class="col-sm-3" style="padding:10px;">
             <div class="card h-100">
                <img src="{{i.img.url}}" class="card-img-top" alt="..." height="250";>
                 <div class="card w-100">
                     <div class="card-body text-default">
                         <h5 class="card-title">{{i.name}}</h5>
                             <p class="card-text">{{i.title}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-warning">View details</a>
                     </div>
  </div>
        </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}